### PR TITLE
fix source_date type for promise editor

### PR DESCRIPTION
**Pull request by sullom101**
fix date needs to be reselected error. @nxmohamad check if server side has validation for the source_date

### CODE REVIEW

**Comment by nxmohamad** [comment]
@sullom101 yup we have it,
````
  source_date: joi
    .string()
    .isoDate()
    .required(),
````

**Comment by nxmohamad** [comment]
@sullom101 can you help update line 369? that error toast is now irrelevant. you can change it to just console.error() or toast but JSON.stringify() the error object

**Comment by nxmohamad** [comment]
after, that this is all good.

**Comment by sullom101** [comment]
@nxmohamad removed the toast message and consoled the error

**Comment by nazreen** [comment]
@sullom101 great, thanks!

**Pull request merged**
